#pragma once

/// Main public header for the ofxGgml addon.
///
/// Include this file to access the runtime, graph builder, inference helpers,
/// model loader, tensor wrapper, shared types, and version macros.

#include "core/ofxGgmlVersion.h"
#include "core/ofxGgmlTypes.h"
#include "core/ofxGgmlResult.h"
#include "core/ofxGgmlHelpers.h"
#include "core/ofxGgmlLogger.h"
#include "core/ofxGgmlMetrics.h"
#include "compute/ofxGgmlTensor.h"
#include "compute/ofxGgmlGraph.h"
#include "inference/ofxGgmlInference.h"
#include "inference/ofxGgmlStreamingContext.h"
#include "inference/ofxGgmlClipInference.h"
#include "inference/ofxGgmlClipCppAdapters.h"
#include "inference/ofxGgmlDiffusionInference.h"
#include "inference/ofxGgmlAceStepBridge.h"
#include "inference/ofxGgmlImageSearch.h"
#include "inference/ofxGgmlLiveSpeechTranscriber.h"
#include "inference/ofxGgmlMediaPromptGenerator.h"
#include "inference/ofxGgmlMusicGenerator.h"
#include "inference/ofxGgmlMilkDropGenerator.h"
#include "inference/ofxGgmlMontagePlanner.h"
#include "inference/ofxGgmlMontagePreviewBridge.h"
#include "inference/ofxGgmlLongVideoPlanner.h"
#include "inference/ofxGgmlVideoEssayWorkflow.h"
#include "inference/ofxGgmlStableDiffusionAdapters.h"
#include "inference/ofxGgmlSpeechInference.h"
#include "inference/ofxGgmlChatLlmTtsAdapters.h"
#include "inference/ofxGgmlCitationSearch.h"
#include "inference/ofxGgmlTtsInference.h"
#include "inference/ofxGgmlVisionInference.h"
#include "inference/ofxGgmlVideoInference.h"
#include "inference/ofxGgmlVideoPlanner.h"
#include "assistants/ofxGgmlChatAssistant.h"
#include "inference/ofxGgmlWebCrawler.h"
#include "assistants/ofxGgmlCodeAssistant.h"
#include "assistants/ofxGgmlCodingAgent.h"
#include "assistants/ofxGgmlWorkspaceAssistant.h"
#include "assistants/ofxGgmlTextAssistant.h"
#include "assistants/ofxGgmlCodeReview.h"
#include "model/ofxGgmlModel.h"
#include "model/ofxGgmlModelRegistry.h"
#include "support/ofxGgmlProjectMemory.h"
#include "support/ofxGgmlEasy.h"
#include "support/ofxGgmlScriptSource.h"
#include "support/ofxGgmlPromptTemplates.h"
#include "core/ofxGgmlCore.h"
